# Generated by Django 3.2 on 2021-04-13 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('ano', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('edicao', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('paginas', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
    ]
